sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nonsochiagunye/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nonsochiagunye/react-test npm test

after_success:
  - docker build -t nonsochiagunye/multi-client ./client
  - docker build -t nonsochiagunye/multi-nginx ./nginx
  - docker build -t nonsochiagunye/multi-server ./server
  - docker build -t nonsochiagunye/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push nonsochiagunye/multi-client
  - docker push nonsochiagunye/multi-nginx
  - docker push nonsochiagunye/multi-server
  - docker push nonsochiagunye/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-149742781583"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY